### ISSUE TITLE
Error from make

### ISSUE THREAD

**Issue by Edu-Ape** [afaerber/lora-modules#2]
Dear Andreas, I followed your instructions but after make, I have the following error:
/lora-modules/linux/net/fsk/netlink.c:80:4: error: ‘const struct genl_ops’ has no member named ‘policy’
   .policy = nlfsk_policy,
    ^~~~~~
/lora-modules/linux/net/fsk/netlink.c:80:13: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   .policy = nlfsk_policy,
My set up is Ubuntu 18.04.4 LTS
GCC 7.5.0
GNU Make 4.1

I'm a newbie in Linux and I don't know if I am doing something wrong. Thank you for your patience
Eduardo (from Argentina)

**Comment by afaerber** [comment]
Hi Eduardo,

I've just updated my Raspberry Pi (arm64) to kernel v5.7-rc5 and don't see any build errors for my GitHub afaerber/linux.git lora-next branch (kernel.org linux-lora.git may differ).

Your Ubuntu LTS kernel might simply be too old for code developed for linux-next?

**Comment by Edu-Ape** [comment]
Hi Andreas, thank you in advance for your fast answer.
Regarding your question, I don't think so, as it is a laptop fresh installation just for learning purposes.
However, I'll try again with my Raspberry Pi 4, with same kernel as you have, and see what happen.
Again, thank you, I'll keep you posted in any case.
Regards

Eduardo

**Comment by Edu-Ape** [comment]
Hi Andreas, thank you in advance for your fast answer.
Regarding your question, I don't think so, as it is a laptop fresh
installation just for learning purposes.
However, I'll try again with my Raspberry Pi 4, with same kernel as you
have, and see what happen.
Again, thank you, I'll keep you posted in any case.
Regards

Eduardo
